# OPEN ELECTIVE PREDICTOR

In [35]:
import pandas as pd
from matplotlib import pyplot as plt 
%matplotlib inline
import numpy as np
import seaborn as sns

In [36]:
df=pd.read_csv(r"C:\Users\Asus\Downloads\UtPredictor\ST2ml.csv", encoding='unicode_escape')

In [37]:
df

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT
0,AADITYA KUMAR,8,36,31.5,29.5,27,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3
1,AAKARSH SINGH,31.5,30,43.5,45.5,39,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9
2,AAKARSH SINGH,17,8,19,23,32,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9
3,AAKASH SAXENA,5.5,1,NaN,13.5,16,36.0,14.4,AAKASH SAXENA,17,24,8,17.5,32,98.5,28.1
4,AANSHI GUPTA,2,21,30,10,20,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,VEDANSH TRIPATHI,15,14,11.5,15,41,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6
337,VISHAL AGRAWAL,15,29,29,18,17,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4
338,VIVEK SINGH,17,6,12,25.5,32,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0
339,YASH MISHRA,37,47,45,42,32,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df=df.dropna()

In [39]:
df_filtered=df.copy()

In [40]:
df_filtered

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT
0,AADITYA KUMAR,8,36,31.5,29.5,27,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3
1,AAKARSH SINGH,31.5,30,43.5,45.5,39,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9
2,AAKARSH SINGH,17,8,19,23,32,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9
4,AANSHI GUPTA,2,21,30,10,20,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3
5,AARUSHI GUPTA,43,47,42.5,45,44,221.5,88.6,AARUSHI GUPTA,64.5,51,61,58,60,294.5,84.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,UTKARSH RAJ,15,16,28.5,20,27,106.5,79.2,UTKARSH RAJ,28,42,48,40,47,205.0,58.6
336,VEDANSH TRIPATHI,15,14,11.5,15,41,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6
337,VISHAL AGRAWAL,15,29,29,18,17,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4
338,VIVEK SINGH,17,6,12,25.5,32,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0
339,YASH MISHRA,37,47,45,42,32,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4

In [41]:
df_filtered["PreferredElective"]=0

In [42]:
df_filtered

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT,PreferredElective
0,AADITYA KUMAR,8,36,31.5,29.5,27,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3,0
1,AAKARSH SINGH,31.5,30,43.5,45.5,39,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9,0
2,AAKARSH SINGH,17,8,19,23,32,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9,0
4,AANSHI GUPTA,2,21,30,10,20,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3,0
5,AARUSHI GUPTA,43,47,42.5,45,44,221.5,88.6,AARUSHI GUPTA,64.5,51,61,58,60,294.5,84.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,UTKARSH RAJ,15,16,28.5,20,27,106.5,79.2,UTKARSH RAJ,28,42,48,40,47,205.0,58.6,0
336,VEDANSH TRIPATHI,15,14,11.5,15,41,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6,0
337,VISHAL AGRAWAL,15,29,29,18,17,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4,0
338,VIVEK SINGH,17,6,12,25.5,32,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0,0
339,YASH MISHRA,37,47,45,42,32,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4,0

In [43]:
len(df_filtered)

289

In [46]:
numeric_columns = ['CHEMISTRY', 'MATHS', 'ELECTRONICS', 'MECHANICAL', 'SOFTSKILLS']
df_filtered[numeric_columns] = df_filtered[numeric_columns].apply(pd.to_numeric, errors='coerce')
print(df_filtered[numeric_columns].dtypes)
df_filtered[numeric_columns] = df_filtered[numeric_columns].fillna(0)  # Replace NaN with 0, adjust based on your use case
df_filtered['PreferredElective'] = df_filtered[numeric_columns].idxmax(axis=1)

CHEMISTRY      float64
MATHS          float64
ELECTRONICS    float64
MECHANICAL     float64
SOFTSKILLS     float64
dtype: object

In [47]:
subject_to_elective_mapping = {
    'CHEMISTRY': 'MaterialScience',
    'MATHS': 'DigitalElectronics',
    'ELECTRONICS': 'SensorInstrumentation',
    'MECHANICAL': 'MechanicsApplied',
    'SOFTSKILLS': 'EnergySciences'
}
df_filtered['PreferredElective'] = df_filtered['PreferredElective'].map(subject_to_elective_mapping)

In [48]:
df_filtered

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT,PreferredElective
0,AADITYA KUMAR,0.0,0.0,0.0,0.0,0.0,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3,MaterialScience
1,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9,MaterialScience
2,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9,MaterialScience
4,AANSHI GUPTA,0.0,0.0,0.0,0.0,0.0,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3,MaterialScience
5,AARUSHI GUPTA,0.0,0.0,0.0,0.0,0.0,221.5,88.6,AARUSHI GUPTA,64.5,51,61,58,60,294.5,84.1,MaterialScience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,UTKARSH RAJ,0.0,0.0,0.0,0.0,0.0,106.5,79.2,UTKARSH RAJ,28,42,48,40,47,205.0,58.6,MaterialScience
336,VEDANSH TRIPATHI,0.0,0.0,0.0,0.0,0.0,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6,MaterialScience
337,VISHAL AGRAWAL,0.0,0.0,0.0,0.0,0.0,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4,MaterialScience
338,VIVEK SINGH,0.0,0.0,0.0,0.0,0.0,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0,MaterialScience
339,YASH MISHRA,0.0,0.0,0.0,0.0,0.0,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4,MaterialScience

In [49]:
np.random.seed(42)
num_rows_per_category = int(0.2 * len(df_filtered))
categories = ["DigitalElectronics", "MaterialScience", "EnergyScience", "Mechanics", "SensorInstrumentation"]
indices_per_category = []
for category in categories:
    indices = np.random.choice(df_filtered.index, num_rows_per_category, replace=False)
    indices_per_category.append(indices)
    df_filtered.loc[indices, 'PreferredElective'] = category
df_filtered

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT,PreferredElective
0,AADITYA KUMAR,0.0,0.0,0.0,0.0,0.0,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3,MaterialScience
1,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9,Mechanics
2,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9,SensorInstrumentation
4,AANSHI GUPTA,0.0,0.0,0.0,0.0,0.0,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3,MaterialScience
5,AARUSHI GUPTA,0.0,0.0,0.0,0.0,0.0,221.5,88.6,AARUSHI GUPTA,64.5,51,61,58,60,294.5,84.1,MaterialScience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,UTKARSH RAJ,0.0,0.0,0.0,0.0,0.0,106.5,79.2,UTKARSH RAJ,28,42,48,40,47,205.0,58.6,MaterialScience
336,VEDANSH TRIPATHI,0.0,0.0,0.0,0.0,0.0,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6,MaterialScience
337,VISHAL AGRAWAL,0.0,0.0,0.0,0.0,0.0,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4,SensorInstrumentation
338,VIVEK SINGH,0.0,0.0,0.0,0.0,0.0,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0,DigitalElectronics
339,YASH MISHRA,0.0,0.0,0.0,0.0,0.0,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4,MaterialScience

In [50]:
len(df_filtered[df_filtered["PreferredElective"]==0])

0

In [51]:
len(df_filtered[df_filtered["PreferredElective"]=="Mechanics"])

44

In [52]:
len(df_filtered[df_filtered["PreferredElective"]=="DigitalElectronics"])

28

In [53]:
len(df_filtered[df_filtered["PreferredElective"]=="SensorInstrumentation"])

57

In [54]:
len(df_filtered[df_filtered["PreferredElective"]=="EnergyScience"])

34

In [55]:
len(df_filtered[df_filtered["PreferredElective"]=="MaterialScience"])

126

In [56]:
df_filtered = df_filtered[df_filtered['PreferredElective'] != 0]

In [57]:
len(df_filtered[df_filtered["PreferredElective"]==0])

0

# Model Training

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [59]:
applicant_df=df_filtered.copy()

In [60]:
label_encoder = LabelEncoder()
applicant_df['PreferredElectiveEncoded'] = label_encoder.fit_transform(applicant_df['PreferredElective'])

In [61]:
applicant_df

,NAME,CHEMISTRY,MATHS,ELECTRONICS,MECHANICAL,SOFTSKILLS,TOTAL,PERCENTAGE,NAMEPUT,CHEMISTRYPUT,MATHSPUT,ELECTRONICSPUT,MECHANICALPUT,SOFTSKILLSPUT,TOTALPUT,PERCENTAGEPUT,PreferredElective,PreferredElectiveEncoded
0,AADITYA KUMAR,0.0,0.0,0.0,0.0,0.0,132.0,52.8,AADITYA KUMAR,31.5,47,38,36.5,44,197.0,56.3,MaterialScience,2
1,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,189.5,75.8,AAKARSH SINGH,53,37,53,63,56,262.0,74.9,Mechanics,3
2,AAKARSH SINGH,0.0,0.0,0.0,0.0,0.0,99.0,39.6,AAKARSH SINGH,33,20,45,30,36,164.0,46.9,SensorInstrumentation,4
4,AANSHI GUPTA,0.0,0.0,0.0,0.0,0.0,83.0,33.2,AANSHI GUPTA,37,34,44,38.5,33,186.5,53.3,MaterialScience,2
5,AARUSHI GUPTA,0.0,0.0,0.0,0.0,0.0,221.5,88.6,AARUSHI GUPTA,64.5,51,61,58,60,294.5,84.1,MaterialScience,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,UTKARSH RAJ,0.0,0.0,0.0,0.0,0.0,106.5,79.2,UTKARSH RAJ,28,42,48,40,47,205.0,58.6,MaterialScience,2
336,VEDANSH TRIPATHI,0.0,0.0,0.0,0.0,0.0,96.5,42.6,VEDANSH TRIPATHI,25.5,31,21.5,36.5,59,173.5,49.6,MaterialScience,2
337,VISHAL AGRAWAL,0.0,0.0,0.0,0.0,0.0,108.0,38.6,VISHAL AGRAWAL,41,50,35.5,25.5,42,194.0,55.4,SensorInstrumentation,4
338,VIVEK SINGH,0.0,0.0,0.0,0.0,0.0,92.5,43.2,VIVEK SINGH,22,21.5,15.5,32.5,52,143.5,41.0,DigitalElectronics,0
339,YASH MISHRA,0.0,0.0,0.0,0.0,0.0,203.0,37.0,YASH MISHRA,41,67,62,52.5,48.5,271.0,77.4,MaterialScience,2

In [62]:
X = applicant_df[['CHEMISTRY', 'MATHS', 'ELECTRONICS', 'MECHANICAL', 'SOFTSKILLS']]
y = applicant_df['PreferredElectiveEncoded']

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [64]:
model = LogisticRegression(max_iter=1000)

In [65]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [66]:
y_pred = model.predict(X_test)

In [67]:
STMARKS = pd.DataFrame({'CHEMISTRY': [20], 'MATHS': [25], 'ELECTRONICS': [38], 'MECHANICAL': [35], 'SOFTSKILLS': [40]})
ELECTIVEPREDICTION = model.predict(STMARKS)
PREDICTEDELECTIVE = label_encoder.inverse_transform([int(ELECTIVEPREDICTION)])

print(f"YOU SHOULD TAKE THE BRANCH: {PREDICTEDELECTIVE[0]}")

YOU SHOULD TAKE THE BRANCH: EnergyScience